<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Switcheroo.LaunchControl</RootNamespace>
    <AssemblyName>Switcheroo.LaunchControl</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="C:\Users\christopher.owen\Projects\master-launch-control\src\LaunchControl.Standard\LaunchControl.Standard.csproj" />
  </ItemGroup>
</Project>
